spring.application.name=Artifact

server.port=9000
line.bot.token=RVkn13fBvvSS6fP1yT8s7BClTvNuMTaFCVI0kuZCsFGwsG7ftpc9joa78aCNYd9SCuKY7BoGyZDVgoBvizl6svRssC/3bFWmQaUg4kWLfNOAa9Vi3miUhF60Gb1AghqIo79VOLg4M6/ZpJB1QxSK1QdB04t89/1O/w1cDnyilFU=
